version: '3.9'
services:
    odoo:
        image: odoo:16.0
        volumes:
            - ./addons-extra:/mnt/extra-addons
            - ./config:/etc/odoo
            - odoo-web-data:/var/lib/odoo
        ports:
            - "8069:8069"
        depends_on:
            - postgres
        restart: unless-stopped
        command: odoo -u all -d prod_rkm --without-demo=all
    postgres:
        image: postgres:14
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: amdin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 5433:80
        restart: unless-stopped
volumes:
    odoo-web-data:
    odoo-db-data:
    pgadmin: